#!/bin/sh

set -euvx

# https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

env | sort

docker image build \
       --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
       --build-arg VCS_REF="$(git rev-parse HEAD)" \
       --tag "${IMAGE_NAME}" \
       .
